CONTRIBUTING.md update patch
devcpune/kaleidoscope pull request #19
Opened 2020-10-06 05:25 UTC by Arsenic-ATG

changes include :- 
1) updation of steps 2 and 3 in chapter 0 of the file
2) made **example** in **chapter 1/step 1** a drop down list ( to decrease the length of the entire file without effecting the amount of information )
3) add link to the LICENSE file under the `License` section fo the file

2020-10-06 12:59 UTC, sayak-sarkar requested changes

2020-10-06 12:59 UTC, sayak-sarkar commented on docs/CONTRIBUTING.md
> +- **source/** -> This directory must contain your acctual project including the complete source code of your project and the `.arproj` file.
```suggestion
- **source/** -> This directory must contain your actual project including the complete source code of your project and the `.arproj` file.
```

2020-10-06 12:59 UTC, sayak-sarkar commented on docs/CONTRIBUTING.md
> +- **README.md** -> The readme file will contain general information about your project. If possible also create a trial link to the project you have created on facebook or instagram in your readme, f
```suggestion
- **README.md** -> The README file will contain general information about your project. If possible also create a trial link to the project you have created on Facebook or Instagram in your README, for further information please refer to Step 3 for the template of this README file.
```

2020-10-07 09:19 UTC, AJV009 commented
@Arsenic-ATG  dont you think there are tooo many commits? (6 commits to merge?)
Maybe you can squash them into one single commit.

2020-10-07 09:33 UTC, Arsenic-ATG commented
@AJV009 branch managers can also do it at the time of merging, by selecting **squash and merge**. But if you want,  I can still squash them in one commit and open a new pull request with the same 🙂.

2020-10-07 09:37 UTC, AJV009 commented
Fine fine! 😅 Don't make another pr now! The manager will squash and commit them!

2020-10-12 15:07 UTC, sayak-sarkar approved these changes

2020-10-12 15:07 UTC, merged